apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia-rc
spec:
  replicas: 2 
  selector:
    app: kubia
  template:
    metadata:
      name: kubia
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: quay.io/jackluxm/kubia
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: kubia
spec:
  selector:
    app: kubia
  ports:
  # Default port used by the image
  - port: 80
    targetPort: 8080
