apiVersion: v1
kind: Namespace
metadata:
  name: filebrowser

---

apiVersion: v1
kind: Pod
metadata:
  name: filebrowser
  namespace: filebrowser
  labels:
    app: filebrowser
spec:
  containers:
  - name: filebrowser
    image: quay.io/jackluxm/filebrowser

---

apiVersion: v1
kind: Service
metadata:
  name: filebrowser
  namespace: filebrowser
spec:
  selector:
    app: filebrowser
  ports:
  - port: 80
    targetPort: 80

