kind: Pod
apiVersion: v1
metadata:
  name: filebrowser
  labels:
    app: filebrowser
spec:
  containers:
  - name: filebrowser
    image: quay.io/jackluxm/filebrowser

---

kind: Service
apiVersion: v1
metadata:
  name: filebrowser
spec:
  selector:
    app: filebrowser
  ports:
  # Default port used by the image
  - port: 80
    targetPort: 80

