kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: testfb-dhanashree

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dh-filebrowser-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-ceph-rbd
---
apiVersion: v1
kind: Pod
metadata:
  name: file-browser-pod
  labels:
    app: file-browser
spec:
  imagePullSecrets:
   - name: regcred
  containers:
   - name: file-browser-container
     image: quay.io/smitaraut/filebrowser:latest
     volumeMounts:
       - name: mypvc
         mountPath: /srv
     ports:
     - containerPort: 80
  volumes:
   - name: mypvc
     persistentVolumeClaim:
       claimName: dh-filebrowser-pvc
       readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: file-browser
spec:
  selector:
    app: file-browser
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
