apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-ceph-rbd
---
apiVersion: v1
kind: Pod
metadata:
  name: filebrowser-pod
  labels:
    app: filebrowser
spec:
  imagePullSecrets:
  - name: regcred
  containers:
  - name: filebrowser-container
    #image: quay.io/smitaraut/filebrowser:latest
    image: quay.io/jackluxm/filebrowser
    volumeMounts:
      - name: filebrowser-pvc
        mountPath: /srv
    ports:
    - containerPort: 80
  volumes:
  - name: filebrowser-pvc
    persistentVolumeClaim:
      claimName: filebrowser-pvc
      # readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: filebrowser
spec:
  selector:
    app: filebrowser
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
