kind: Pod
apiVersion: v1
metadata:
  name: http-echo
  labels:
    app: http-echo
spec:
  containers:
  - name: http-echo
    image: quay.io/jackluxm/http-echo:0.2.3
    args:
    - "-text=hello world"
---
kind: Service
apiVersion: v1
metadata:
  name: http-echo
spec:
  selector:
    app: http-echo
  ports:
  # Default port used by the image
  - port: 80
    targetPort: 5678

