apiVersion: v1
kind: Pod
metadata:
  name: u18-runasroot
spec:
  containers:
    - name: u18
      image: quay.io/jackluxm/u18
      command: ["/bin/sleep", "3650d"]
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsUser: 0

