apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: u18vol 
  #namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  #storageClassName: sc1
